iris-objs += iris_probe.o \
             iris_core.o \
             iris_vidc.o \
             iris_vdec.o \
             iris_state.o \
             iris_ctrls.o \
             iris_helpers.o \
             iris_hfi.o \
             iris_hfi_response.o \
             iris_hfi_queue.o \
             iris_hfi_packet.o \
             resources.o \
             firmware.o \
             vpu_common.o \
             vpu_iris3.o \
             platform_common.o \
             platform_sm8550.o

obj-$(CONFIG_VIDEO_QCOM_IRIS) += iris.o
