iris-objs += iris_probe.o \
             iris_core.o \
             iris_state.o \
             iris_helpers.o \
             iris_hfi.o \
             iris_hfi_queue.o \
             iris_hfi_packet.o \
             resources.o \
             firmware.o

obj-$(CONFIG_VIDEO_QCOM_IRIS) += iris.o
